---
title: "Chloropleths in Leaflet"
author: "ixpantia"
date: "November 2, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(geojsonio)
library(leaflet)
```


## ejemplo Peru

https://rstudio.github.io/leaflet/choropleths.html


```{r}
states <- geojsonio::geojson_read("json/peru_departamental_simple.geojson", what = "sp")
class(states)

m <- leaflet(states) %>%
  setView(-75, -10, 5) %>%
  addTiles()

m %>% addPolygons()


bins <- c(0, 10, 20, 50, 100, 200, 500, 1000, Inf)
pal <- colorBin("YlOrRd", domain = states$COUNT, bins = bins)

m %>% addPolygons(
  fillColor = ~pal(COUNT),
  weight = 1,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7)
```

## Con interaccion


```{r}

labels <- sprintf(
  "<strong>%s</strong><br/>%g people / mi<sup>2</sup>",
  states$NOMBDEP, states$COUNT
) %>% lapply(htmltools::HTML)

m %>% addPolygons(
  fillColor = ~pal(COUNT),
  weight = 1,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7,
  highlight = highlightOptions(
    weight = 5,
    color = "#666",
    dashArray = "",
    fillOpacity = 0.7,
    bringToFront = TRUE),
 label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"))

```


# Nivel distrital

```{r}
states <- geojsonio::geojson_read("json/peru_distrital_simple.geojson", what = "sp")
class(states)

m <- leaflet(states) %>%
  setView(-75, -10, 5) %>%
  addTiles() 
m %>% addPolygons()

bins <- c(0, 1000, 10000, 100000, 1000000, Inf)
pal <- colorBin("YlOrRd", domain = states$AREA_MINAM, bins = bins)

m %>% addPolygons(
  fillColor = ~pal(AREA_MINAM),
  weight = 0.5,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7)
```
